spring: 
  datasource-primary:
    driver-class-name: org.postgresql.Driver 
    jdbcUrl: jdbc:postgresql://localhost:5433/datasource?reWriteBatchedInserts=true
    schema: cts_dataset
    username: postgres
    password: home
    separator: ^;
---
configs:
   threadParams:
      initDelayed: 30
      delayBetween: 40
   tempDirectory: E:/Development/temp_downloads/
   tables:
      - agency
      - feed_info
      - trips
      - calendar_dates
      - routes
      - stop_times
      - stops