spring: 
  datasource:
    driver-class-name: org.postgresql.Driver 
    jdbcUrl: jdbc:postgresql://localhost:5432/sandbox
    schema: cts_transit_feed #classpath:sql/schema.sql
    username: postgres
    password: home
    separator: ^;
---
tables:
   - agency
   - feed_info
   - trips
   - calendar_dates
   - routes
   - stop_times
   - stops