spring:
  datasource-primary:
    driver-class-name: org.postgresql.Driver 
    jdbcUrl: jdbc:postgresql://localhost:5434/sandbox
    schema: test_gtfs
    username: postgres
    password: home
    separator: ^;